name: dutclock
summary: Shows the time until the beginning / end of the lesson 
description: |
      Work only for DUT
version: git
grade: stable
base: core20

confinement: devmode

parts:
  dutclock:
    plugin: go
    source-type: git
    source: https://github.com/FoPPi/DUTclock